### PR TITLE
update to zeppelin 0.6.1

### PR DESCRIPTION
**Pull request by zutherb**
can you please push the docker image to docker hub.

i used zutherb/zeppelin:0.6.1 to try if it works

### CODE REVIEW

**Comment by keithchambers** [comment]
Hi @zutherb! Thank you for this PR!

I'll test this today. Assuming it works I should be able to push an update tomorrow.

**Comment by zutherb** [comment]
any update???

**Comment by joerg84** [comment]
@mgummelt @keithchambers  PTAL.

**Comment by zutherb** [comment]
@keithchambers  did you look on the pull request??

**Comment by triclambert** [comment]
Please don't forget to submit a PR to mesosphere/universe.  /cc @ryadav88

**Pull request merged**
